name: CI
on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Worm
        run: pip3 install .
      - name: Perform checks
        run: echo 'exit' | worm
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Worm
        run: pip3 install .
      - name: Perform checks
        run: echo 'exit' | worm
